server:
  port: 8083
aws:
  iam:
    user:
      access-key: AKIAVDKEOUEERDOATQCC
      secret-key: 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
  dynamo:
    service-endpoint: dynamodb.us-east-1.amazonaws.com
    signing-region: us-east-1
