server:
  port: 8083
aws:
  iam:
    user:
      access-key: ${aws.access-key}
      secret-key: ${aws.secret-key}
  dynamo:
    service-endpoint: dynamodb.us-east-1.amazonaws.com
    signing-region: us-east-1
